# run.ps1 runs a checks script (shots.ahk, timing.ahk, stay.ahk or keys.ahk) against a source root, which stays untouched: the
# AutoHotkey wrapper (and, for timing and stay, an instrumented COPY of the root's sources) is generated under build\checks\gen\. Options:
#   shots   [-Out <dir>] [-Tag <name>] [-Theme light,dark] [-Scenes abcdm]       timing  [-Out <dir>] [-Tag <name>] [-Wrap <fn>,...]
#   stay    [-Out <dir>] [-Tag <name>]   (stay-open timings)                     keys    (Win+Q: no Start menu, no menu bar)
# -Root is the source folder to check (default: the repo root); point it at another one, such as an exported older commit, to compare
# before and after. -Tag names the run (default: the root's folder name); -Out defaults to build\checks\<tag>; -Ahk defaults to the
# first AutoHotkey v2 found under $env:ProgramFiles or $env:LOCALAPPDATA\Programs; -Validate only load-checks (no windows, no input).
# Run from the repo root:  powershell -ExecutionPolicy Bypass -File tools\checks\run.ps1 shots|timing|stay|keys [-Root <dir>] ...
#                          powershell -ExecutionPolicy Bypass -File tools\checks\run.ps1 shots -Theme light -Scenes a
#                          powershell -ExecutionPolicy Bypass -File tools\checks\run.ps1 timing -Validate
# Exit code: 0 ok, 1 a check failed (keys), 2 the 2-minute safety exit, 3 an error in the run, 4 the privacy guard refused a capture
# (shots) or no screen, so nothing was shown or sent (stay, keys), 5 a stray AutoHotkey window was already on screen (nothing was
# started). Keep hands off the mouse and keyboard while it runs (about 40 s, per theme for shots; 25 s for keys), except with -Validate.
param(
    [Parameter(Mandatory, Position = 0)][ValidateSet('shots', 'timing', 'stay', 'keys')][string]$Mode,
    [string]$Root,                               # the source folder to check (default: the repo root), e.g. an exported older commit
    [string]$Out, [string]$Tag,
    [string[]]$Theme = @('light', 'dark'), [string]$Scenes = 'abcdm',
    [string[]]$Wrap = @(),                       # timing: more functions to wrap and time (ScrollTick, SelectTile, PaneWheel always)
    [switch]$Validate,                           # only generate and load-check (no windows, no input)
    [string]$Ahk                                 # AutoHotkey64.exe (default: the first of the two usual v2 install paths that exists, below)
)
$ErrorActionPreference = 'Stop'
$Theme = @($Theme -split ',')                    # powershell -File passes a list such as light,dark as one string
$Wrap = @($Wrap -split ',')
$checks = $PSScriptRoot
$repo = Split-Path (Split-Path $checks)          # tools\checks -> the repo root
if (-not $Root) { $Root = $repo }
if (-not $Ahk) {
    $candidates = @("$env:ProgramFiles\AutoHotkey\v2\AutoHotkey64.exe", "$env:LOCALAPPDATA\Programs\AutoHotkey\v2\AutoHotkey64.exe")
    $Ahk = $candidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
    if (-not $Ahk) { throw "AutoHotkey v2 not found (looked for $($candidates -join ' and ')): pass -Ahk <path to AutoHotkey64.exe>" }
}
$Root = (Resolve-Path -LiteralPath $Root).Path.TrimEnd('\')
if (-not (Test-Path -LiteralPath "$Root\meowtab.ahk")) { throw "no meowtab.ahk in $Root" }
if (-not $Tag) { $Tag = Split-Path $Root -Leaf }
if (-not $Out) { $Out = Join-Path $repo "build\checks\$Tag" }
$Out = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Out)
$gen = Join-Path $repo "build\checks\gen\$Tag-$Mode"
if (Test-Path $gen) { Remove-Item $gen -Recurse -Force }
New-Item -ItemType Directory -Force $gen, $Out | Out-Null
$utf8 = New-Object Text.UTF8Encoding($false)

# The wrapper: warnings to stdout (never a blocking dialog), the root's path, a new empty data folder (the user's own settings
# are never read or changed), then the includes.
$head = @"
#Requires AutoHotkey v2.0
#SingleInstance Off
#Warn All, Off
#Warn VarUnset, StdOut
#Warn Unreachable, StdOut
; generated by run.ps1 ($Mode, $Tag) for the source root $Root
SRC_ROOT := "$Root"
DATA_DIR := A_Temp "\meowtab-$Mode-" A_TickCount
OnExit((*) => (DirExist(DATA_DIR) && DirDelete(DATA_DIR, true), 0))

"@

$runs = New-Object 'System.Collections.Generic.List[string[]]'   # one argument list per AutoHotkey process
if ($Mode -eq 'shots') {
    $main = "#Include $Root\meowtab.ahk`n#Include $checks\lib.ahk`n#Include $checks\shots.ahk`n"
    # One process per theme, so both start alike (the first real mouse press in a process is special at HEAD, see shots.ahk "m").
    if ($Validate) { $runs.Add([string[]]@($Out, ($Theme -join ','), $Scenes)) }
    else { foreach ($t in $Theme) { $runs.Add([string[]]@($Out, $t, $Scenes)) } }
}
elseif ($Mode -eq 'timing') {
    # An instrumented copy: each frame function that exists is renamed <name>__orig and wrapped by a function of the old name that
    # times the call, so timers and callers go through it. The root's files are only read.
    $src = Join-Path $gen 'src'
    New-Item -ItemType Directory $src | Out-Null
    $texts = @{}
    foreach ($f in Get-ChildItem -LiteralPath $Root -Filter *.ahk -File) { $texts[$f.Name] = [IO.File]::ReadAllText($f.FullName) }
    $tmpl = @'

@FN@(p*) {
    t := Qpc()
    try return @FN@__orig(p*)
    finally TimeLog("@FN@", Qpc() - t)
}
'@
    $wrappers = "; generated by run.ps1: timing wrappers`n"
    foreach ($fn in (@('ScrollTick', 'SelectTile', 'PaneWheel') + $Wrap | Select-Object -Unique)) {
        $rx = [regex]"(?m)^$([regex]::Escape($fn))\("
        $hits = @($texts.Keys | Where-Object { $rx.IsMatch($texts[$_]) })
        if ($hits.Count -eq 0) { Write-Host "wrap: $fn is not defined in this source, skipped"; continue }
        if ($hits.Count -gt 1 -or $rx.Matches($texts[$hits[0]]).Count -gt 1) { throw "wrap: $fn is defined more than once" }
        $texts[$hits[0]] = $rx.Replace($texts[$hits[0]], "${fn}__orig(", 1)
        $wrappers += $tmpl.Replace('@FN@', $fn)
        Write-Host "wrap: $fn (in $($hits[0]))"
    }
    foreach ($name in $texts.Keys) { [IO.File]::WriteAllText((Join-Path $src $name), $texts[$name], $utf8) }
    [IO.File]::WriteAllText("$gen\wrap.ahk", $wrappers, $utf8)
    $main = "#Include $src\meowtab.ahk`n#Include $gen\wrap.ahk`n#Include $checks\lib.ahk`n#Include $checks\timing.ahk`n"
    $runs.Add([string[]]@($Out, $Tag))
}
elseif ($Mode -eq 'stay') {
    # A copy in which meowtab.ahk's CollectWindows is renamed CollectWindows__orig: stay-seam.ahk defines it again, listing only the
    # demo windows (meowtab-classic.ahk has its own, and isn't included). The root's files are only read.
    $src = Join-Path $gen 'src'
    New-Item -ItemType Directory $src | Out-Null
    $rx = [regex]'(?m)^CollectWindows\('
    foreach ($f in Get-ChildItem -LiteralPath $Root -Filter *.ahk -File) {
        $t = [IO.File]::ReadAllText($f.FullName)
        if ($f.Name -eq 'meowtab.ahk') {
            if ($rx.Matches($t).Count -ne 1) { throw "expected one CollectWindows( definition in $Root\meowtab.ahk" }
            $t = $rx.Replace($t, 'CollectWindows__orig(', 1)
        }
        [IO.File]::WriteAllText((Join-Path $src $f.Name), $t, $utf8)
    }
    $main = "#Include $src\meowtab.ahk`n#Include $checks\lib.ahk`n#Include $checks\stay-seam.ahk`n#Include $checks\stay.ahk`n"
    $runs.Add([string[]]@($Out, $Tag))
}
else {
    # keys: the app starts with SWITCH_KEYS=Win+Q in the new data folder (the stay-open shortcut stays the default, Ctrl+Alt+Tab).
    $main = 'DirCreate(DATA_DIR), IniWrite("Win+Q", DATA_DIR "\settings.ini", "settings", "SWITCH_KEYS")' + "`n#Include $Root\meowtab.ahk`n#Include $checks\keys.ahk`n"
    $runs.Add([string[]]@())
}

$wrapper = Join-Path $gen "$Mode.ahk"
[IO.File]::WriteAllText($wrapper, $head + $main, $utf8)
Write-Host "run: $Mode on $Root`nwrapper: $wrapper`nout: $Out"
if (-not (Test-Path -LiteralPath $wrapper)) { throw "no wrapper at $wrapper" }
$ErrorActionPreference = 'Continue'
$worst = 0
foreach ($a in $runs) {
    # The argument list is a typed string[] of WHOLE arguments. (An `if` that yields a one-element array hands back a bare string,
    # and splatting a string passes it one character per argument: AutoHotkey then tried to open the script "/".)
    [string[]]$argv = @('/ErrorStdOut')
    if ($Validate) { $argv = @('/Validate') + $argv }
    $argv = $argv + @($wrapper) + $a
    Write-Host "cmd: $Ahk $($argv -join ' ')"
    $o = & $Ahk $argv | Out-String                            # the pipe makes PowerShell wait for the GUI process
    $code = $LASTEXITCODE
    $o
    "exit code: $code"
    if ($code -ne 0 -and $worst -eq 0) { $worst = $code }
    if ($code -ne 0 -and $code -ne 4) { break }               # 4 = a refused capture: the next theme can still run; anything else stops
}
exit $worst
